### ISSUE TITLE
hsnd2wav makes janky .wav files

### ISSUE THREAD

**Issue by biggnome** [avaraline/Avara#156]
I was attempting to extract resources from some archived level files per [that other thread](https://github.com/avaraline/Avara/discussions/154), and I noticed some peculiarities in the resulting WAV files. I'm almost certain the original resources were 8-bit, but the resulting WAV files are 16-bit with the LSB padded with 1's (at least as far as I can tell): this results in the audio being biased fully positive with headroom reduced by half, and the offset producing an approximately -12dBFS click upon conventional playback, although I have not observed this in-game. (The sample rate of ~11kHz is about what I'd expect, and I'm sure that's probably accurate.)

I have no way of knowing whether this was a conversion error on my part, or a peculiarity of Avara's sound engine, or something esoteric like an issue with converting unsigned 8-bit to signed 16-bit, but I thought I ought to mention it. I have experienced an intermittent issue in the '4 Isles' level I posted wherein most of the audio is occasionally silenced in a way that would be consistent with DC offset starving the system of headroom, but I couldn't verify that for certain.

I've attached screenshots of the original & repaired audio, as well as the silence towards the end of the file (give or take some slop in Audition's DC offset removal).

![dcaudio](https://user-images.githubusercontent.com/12508219/107506474-f7929080-6b52-11eb-9ee7-9ecbdc53753c.png)
![dchex](https://user-images.githubusercontent.com/12508219/107506477-f82b2700-6b52-11eb-8b73-d470d734653a.png)

**Comment by assertivist** [comment]
You are [absolutely right](https://github.com/avaraline/Avara/blob/master/src/hsnd2wav.cpp#L44-L47). Have I mentioned that we _barely_ know what we're doing here? what I think I'm hearing you say is that the samples need to be from -127 to 127? and not 0-255?

**Comment by biggnome** [comment]
Depends on the format. Generally I would say yes--that at least would obviate the problem of DC offset, with these caveats: 0-255 is appropriate for an output with unsigned 8-bit format, -128-127 is appropriate for a signed format (which is almost universal for WAV, apart from the occasional unsigned 8)--if the output file is 8-bit as well, then Bob's your uncle; if it's 16-bit, that'll sound fine, just quiet unless it's normalized to -32768-32767. If I have some time later I'll tinker around with the WAV headers and see if that elucidates anything, although I think we're probably on the right track.

By the way, while I don't have any programming experience to speak of, I am an audio engineer with a moderate amount of experience with the nuts and bolts of digital audio--I'd be happy to contribute or advise in any way I can.

**Comment by assertivist** [comment]
So like avara had custom huffman encoding in those resource forks. There was some kind of program you had to run to compress your sound. I don't remember how this was documented, I might have read about how to do it on a forum or something. In any case, we have the original code ported to load the weird encoding and turn that into samples. Avara apparently uses unsigned *four bit* samples for these (I am guessing because mono four bits stereo eight bits :question:) because the numbers that I get for a sample are 0 through 127. 

So that means that dividing by 255 was indeed halving the amplitude of the sample. And we weren't properly changing it to signed data. I got the same picture in audacity:

![2021-02-10-192328_636x153_scrot](https://user-images.githubusercontent.com/1486313/107607303-b56a5d00-6bed-11eb-9cb0-8a0576be6d4f.png)


What i did instead is

1. divide by 127.0f to get a 0-1 range float
2. subtract .5f for unsigned -> signed
3. save to the 16 bit audio file

This makes the wave form look much better:
![2021-02-10-195514_639x155_scrot](https://user-images.githubusercontent.com/1486313/107607312-bdc29800-6bed-11eb-8707-e006a815fb3a.png)

Still not quite sure if its perfect. It's still a 16 bit file because i changed it to float.

The sample rate is 22254hz and then each sound can set its own factor of that sample rate. most of them are set to 1.0, ive seen some longer sounds that had .5 so ~11khz

Does that sound crazy? Going to push this change through since it's only in hsnd2wav and nothing depends on that yet.

**Comment by assertivist** [comment]
Try 'er again after #157 is merged.

**Comment by biggnome** [comment]
Huh. Weird, wild stuff. I'm unfamiliar with Huffman encoding, but from what I could find at a glance, that appears to be a form of lossless data compression which, if that's so, shouldn't have any bearing on the integrity of the audio (that, or some form of compansion, which--basically likewise). As an aside, as far as I'm aware, PCM audio is always signed integer, except for 8-bit which can optionally be unsigned--hence 0-255, which accounts for why dividing by 255 was halving the amplitude and biasing positive when transcoding to signed 16-bit (32-bit and up can be either integer or floating point, but that's way more advanced of anything that was going on with computer audio 25 years ago).

Anyway, I would probably scale things by 2.f after subtracting .5f to normalize from -0.5-0.5 to -1-1 unless there's a good reason not to--the audio is qualitatively the same either way, except that the former plays back 6dB quieter than the original would have; but in any case, yeah, that should be a lot better behaved centered on zero like that.

Re: sample rate, gotcha, that sounds totally plausible. I did do a quick double check and everything plays back at the correct speed/pitch in both the original and the port, so I'm totally confident that that's accurate. I just wondered because 22254Hz is a really weird rate to use, but like I mentioned, weird sample rates were relatively common in multimedia back then.

**Comment by assertivist** [comment]
Thank you, you fixed it. they sounded fuzzy and multiplying by two makes them sound nice and crunchy. Check with the latest patch i just pushed #158 and make a pull request adding yourself to CONTRIBUTORS.md!
