### ISSUE TITLE
Spectator mode

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#16]

**Comment by dcwatson** [comment]
To elaborate a little bit, I'm thinking of three things, probably in the order in which they should be implemented:

1. An overhead spectator mode when you die, instead of locked where your scout is
2. A "follow player" mode, where after you die you can cycle through players to see what they see
3. A non-player spectator mode, where you don't even have to be in the game to watch what's going on (either via 1 or 2)

**Comment by rherriman** [comment]
Alternatively spectator mode could cycle through 1 and 2, as though overhead view was at the beginning or end of the player list.

Another consideration is that we may not want to cycle through ALL players or enable overhead view if it is a team game.

**Comment by rherriman** [comment]
Not sure I like the idea of entering free camera mode whenever in limbo, the player may not even register that they died before they reincarnate. Spectator mode should probably only activate after all lives are lost.
