### ISSUE TITLE
ALF branch level coverage

### ISSUE THREAD

**Issue by dcwatson** [avaraline/Avara#164]
ALF conversion test cases:
- ~~Medievos~~
- Disk-o-tech light
- ~~'god' - T Plus Five A~~
- Falghen - Oddities

LEDI:
~~not-aa missing levels?~~
~~all sets: levels out of order~~

**Comment by dcwatson** [comment]
The ALF problems above were taken care of in https://github.com/avaraline/Avara/commit/c6d99606d0f81b51adbdb1128b8134ea4b7886a5

**Comment by assertivist** [comment]
Disk-o-tech is accurate to the original

the problem in Falghen was a stray script line that was just said `wallHeight` with no assignment. There was a complete object statement right before that though, so what I did was split the script chunk by `\n\n` before passing it to the script parser, which doesn't really change the behavior, but allows the full valid statement ahead of the problem statement to be parsed just fine.
fixed in https://github.com/avaraline/Avara/commit/3dc769a8db8d0b58288fc9c569e729c38fe98df5
