### ISSUE TITLE
Walking forward halted by firing a grenade

### ISSUE THREAD

**Issue by iksbob** [avaraline/Avara#180]
Launching a grenade (press and release e) while walking forward (holding w) halts forward motion. Not seeing the issue on any other keys. Pulled & built July 2 on Ubuntu 20.04.2 (X11, GNOME 3.36.8) on a Thinkpad Yoga 12 (i7 5600, integrated graphics, 8GB RAM).

See https://www.youtube.com/watch?v=In5gv9Xzbr8 for demonstration.

**Comment by tra** [comment]
Is the "E" key mapped to anything in addition to "fire" in your prefs.json?

**Comment by iksbob** [comment]
Yep: "loadGrenade". Though the bug persists even if I remove both of those. Give the key no function at all and it will still stop forward motion.

**Comment by jmunkki** [comment]
Some keyboards may have issues detecting more than a few keys held down at once due to hardware limitations? The symptoms indicate this might be the cause. If that's the case, there's no software fix, as far as I know.

**Comment by assertivist** [comment]
There's no way to know for sure without seeing your keyboard's circuitry, but typically cheaper keyboard circuits group keys together for rollover to save on components. Rollover is how your keyboard hardware can determine how many keys are held at one time. This is not important for most keyboard use cases, and you usually only hold modifiers rather than letters, so modifiers get handled specially.

Considering that W/E are right next to each other on the same row for US English keyboards, I would gather that's what the issue is. A simple way to check if this is a problem is to hold both left and right shift buttons and attempt to type "The quick brown fox jumps over the lazy dog". If you don't have good rollover, you will end up with something like "HE QUIK BROWN FO JUPS OER HE LA DOG"

I've seen several Lenovo forum posts complaining about this issue on the P50, Yoga, etc.
