### ISSUE TITLE
Registers with tracker regardless of checkbox

### ISSUE THREAD

**Issue by ryansommers** [avaraline/Avara#312]
When hosting with "Register with Tracker" unchecked, the server still shows up at https://avara.io and pings Discord.

**Comment by Ymihere03** [comment]
I can't reproduce this on Windows. I don't have a way to test other OSes.

**Comment by assertivist** [comment]
Checkbox seems to work OK on Fedora as well. @ryansommers do you happen to remember reproduction steps, or can you still get this to happen? I am assuming you toggled it several times over the course of trying to get a game set up with two players locally on the same public server. 

This may have been fixed with @tra 's improvements to preferences handling in/around #338

**Comment by tra** [comment]
I don't think that #338 would have fixed that but I haven't seen this behavior since adding the `-s` option (starts server without registering).

**Comment by tra** [comment]
This isn't exactly what @ryansommers describes but pretty close.  Start a server with the Register box unchecked.  Then stop the server and check the Register box after the server stops.  That causes it to show up on the tracker.
