### ISSUE TITLE
net-99/Sands has misaligned shadow object

### ISSUE THREAD

**Issue by dcwatson** [avaraline/Avara#358]
![Screenshot_20230710_222827](https://github.com/avaraline/Avara/assets/1486313/34442100-a68b-491e-b9c9-4fd6f4d77463)

Strong hint that it is also the wrong color, purple instead of black. Clearly getting caught up with another object's definition during conversion or ALF parsing.

**Comment by rherriman** [comment]
Gotta agree. Really seems like it's using the wrong arc segment during conversion to ALF.

**Comment by assertivist** [comment]
Turns out that the ALF conversion works great, it is even including some `TeamColor` elements that I think were used for ScoreKeeper. This is what's interfering with the shadow element. 
```
...
 <Teleporter shape="0" status="false" win="1000" start="@winTeam" activeRange="2000" color="#ff7498" color.1="#000000" cx="43.05555555555556" cz="46.80555555555556" angle="0" />
 <!-- there are other ones in the file, but if i comment these five out, the shadow works again. -->
  <TeamColor mask="T5" color="#581d9a" color.1="#8e5cd6" cx="38.40277777777778" cz="58.333333333333336" r="1.4583333333333357" angle="135" />
  <TeamColor mask="T4" color="#92185b" color.1="#d869bb" cx="38.333333333333336" cz="60.833333333333336" r="1.4583333333333357" angle="135" />
  <TeamColor mask="T6" color="#005891" color.1="#1391fd" cx="38.19444444444444" cz="63.125" r="1.4583333333333357" angle="135" />
  <TeamColor mask="T3" color="#921400" color.1="#fe2700" cx="38.263888888888886" cz="68.125" r="1.4583333333333357" angle="135" />
  <TeamColor mask="T2" color="#8b8e00" color.1="#e8f900" cx="38.125" cz="65.625" r="1.4583333333333357" angle="135" />
  <Hologram shape="100" speed="0" mask="T1" color="#00fa9e" color.1="#010101" cx="75.48611111111111" cz="66.04166666666667" angle="0" />
  ...
  ```
I'm not sure exactly how, but something about the state loaded when attempting to parse the `TeamColor` element is left over and used when parsing the shadow element. This is touchy because we [usually need to load any and all parameters on an element into our context](https://github.com/avaraline/Avara/blob/main/src/level/LevelLoader.cpp#L156-L162) before we create a game object, not knowing if `LinkLoose` will actually make something and use our parameters later on.
