### ISSUE TITLE
avara github.io page with binaries that include SDL and SDL_net?

### ISSUE THREAD

**Issue by doomlaser** [avaraline/Avara#36]
I'm having trouble getting friends to download this port and the SDL and SDL_net dependencies are causing some friction. 

Would it be possible to create binaries that include these two dependencies and maybe make a nice avara.github.io page with download lniks for brain-dead 2 minute frictionless installs? You guys have done great work with this port and I'd love to see it get some adoption from the non tech elite...

**Comment by assertivist** [comment]
https://vastan.net/avara-builds/latest/

This is the best we have. There have been compatibility issues reported on Windows 7 and versions of MacOS before El Capitan. On Linux you will probably have to manually tell SDL to use ALSA instead of PulseAudio if you use it.

The tracker interface doesn't work yet, the UI has some bugs, and it'll crash if you type enough unicode. There's also a list of things we really want to do before promoting to a wider audience, not limited to a spectator feature, proper lighting and shapes, possibly increasing the framerate. But you can definitely play this.

**Comment by doomlaser** [comment]
You're probably right about those features really helping with adoption. I'd love to see 60fps Avara become a reality. I just love this classic game and the quality of the port so far and I want to play some net games.

I do think it would be wise going forward to package the binaries with SDL & SDL_net, requiring the separate install of them. That's a bit of non-intuitive friction even for diehard fans.

**Comment by assertivist** [comment]
`make macapp` and `make winapp` are supposed to copy the libs/dlls respectively into the correct place in the resulting package, do the binaries I linked not work without installing SDL stuff?

**Comment by doomlaser** [comment]
make macapp includes SDL and SDL_net properly, my bad. Didn't know about make macapp. Closing this issue. Thanks!
